---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime_deployment
  labels:
    app: prime-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-clone
  template:
    metadata:
      labels:
        app: prime-clone
    spec:
      containers:
      - name: prime-container
        image: dockerpavank/prime-clone:latest
        ports:
        - containerPort: 3000
...
