---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
  labels:
    app: prime-clone
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: prime-clone
  type: NodePort
...
